export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const SILENT_LOGIN = "SILENT_LOGIN";
export const LOG_OUT = "LOG_OUT";

export const GET_USER = "GET_USER";
export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";

export const SET_SONGS = "SET_SONGS";

export const SET_SONGS_NEW_PLAYLIST = "SET_SONGS_NEW_PLAYLIST";
export const SET_NAME_NEW_PLAYLIST = "SET_NAME_NEW_PLAYLIST";
export const CREATE_NEW_PLAYLIST = "CREATE_NEW_PLAYLIST";

export const SET_CURRENT_SONG = "SET_CURRENT_SONG"
export const PLAY_NEXT_SONG = "PLAY_NEXT_SONG"
export const PLAY_PREVIOUS_SONG = "PLAY_PREVIOUS_SONG"

export const SET_CURRENT_PLAYLIST = "SET_CURRENT_PLAYLIST"
export const SET_SONGS_IN_PLAYLIST = "SET_SONGS_IN_PLAYLIST"
export const REORDER_SONGS_IN_PLAYLIST = "REORDER_SONGS_IN_PLAYLIST"

export const CHANGE_SONG = "CHANGE_SONG"
export const SET_PLAY = "SET_PLAY"

export const UPLOAD_TRACK = "UPLOAD_TRACK";
export const SAVE_USER_SETTINGS = "SAVE_USER_SETTINGS";

export const SET_LOADING = "SET_LOADING";